### ISSUE TITLE
Any sleep or wait in tests should be preceeded by log statement 

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1792]
https://github.com/fedimint/fedimint/pull/1781#discussion_r1119029229

**Comment by PaarthAgarwal** [comment]
Hi I'd like to work on this issue.

**Comment by justinmoon** [comment]
Assigned you @PaarthAgarwal. Feel free to make a small draft PR before you're finished and we can give you some feedback.

**Comment by PaarthAgarwal** [comment]
@justinmoon I read through the comment and understood the issue but what do you mean by "log statement"? Is there something specific you want to print?

**Comment by elsirion** [comment]
To enforce this, can we forbid `sleep` in test and instead define a `sleep_in_test(comment: impl AsRef<str>)` utility method that will do the right thing (tm)?

**Comment by 15IITian** [comment]
> To enforce this, can we forbid `sleep` in test (using semgrep) and instead define a `sleep_in_test(comment: impl AsRef<str>)` utility method that also logs the sleep?

This is better option as It will always bind developers to have log statement before any sleep line as compared to one manually writting them.

**Comment by kernelkind** [comment]
I'm going to work on this. All of the testing locations appear to be:
```
  - fedimint-testing/
  - fedimint-wasm-testing/
  - fedimint-wasm-tests/
  - fedimint-load-test-tool/
  - modules/fedimint-dummy-tests/
  - modules/fedimint-wallet-tests/
  - modules/fedimint-ln-tests/
  - modules/fedimint-mint-tests/
  - gateway/ln-gateway/tests/
  - fedimint-client/src/backup/tests.rs
  - devimint/src/tests.rs
```

The following is the addition I'm making to `.config/semgrep.yaml`:
```
- id: avoid-direct-sleep-in-tests
  patterns:
    - pattern: sleep($X)
    - pattern-not-inside: sleep_in_test($X, $Y)
  paths:
    include:
      - fedimint-testing/
      - fedimint-wasm-testing/
      - fedimint-wasm-tests/
      - fedimint-load-test-tool/
      - modules/fedimint-dummy-tests/
      - modules/fedimint-wallet-tests/
      - modules/fedimint-ln-tests/
      - modules/fedimint-mint-tests/
      - gateway/ln-gateway/tests/
      - fedimint-client/src/backup/tests.rs
      - devimint/src/tests.rs
  message: "Direct use of sleep in tests is discouraged. Use sleep_in_test instead."
  languages: [rust]
  severity: WARNING
  ```

Since they span a few different crates, I would like to create a new library crate called `testing_utils` and place the `sleep_in_test` function inside. Then, each crate that requires the `sleep_in_test` function would add the crate as a dependency in it's `cargo.toml`. Right now, the only one that would need it is `fedimint-testing`
