### ISSUE TITLE
fedimint-core fails as an external dependency

### ISSUE THREAD

**Issue by douglaz** [fedimint/fedimint#3489]
Creating a minimal rust project including `fedimint-core`
```toml
[package]
name = "test-fedimint-deps"
version = "0.1.0"
edition = "2021"

[dependencies]
fedimint-core = { git = "https://github.com/fedimint/fedimint", rev = "2a1a5f21de3d3ddfe8600b25119543d0835f7300" }

[patch.crates-io]
secp256k1-zkp = { git = "https://github.com/dpc/rust-secp256k1-zkp/", branch = "sanket-pr" }
```

Will result in:
```bash
$ cargo build
   Compiling tbs v0.1.0 (https://github.com/fedimint/fedimint?rev=2a1a5f21de3d3ddfe8600b25119543d0835f7300#2a1a5f21)
   Compiling fedimint-logging v0.1.0 (https://github.com/fedimint/fedimint?rev=2a1a5f21de3d3ddfe8600b25119543d0835f7300#2a1a5f21)
   Compiling fedimint-derive v0.1.0 (https://github.com/fedimint/fedimint?rev=2a1a5f21de3d3ddfe8600b25119543d0835f7300#2a1a5f21)
   Compiling fedimint-core v0.1.0 (https://github.com/fedimint/fedimint?rev=2a1a5f21de3d3ddfe8600b25119543d0835f7300#2a1a5f21)
error[E0433]: failed to resolve: could not find `Builder` in `task`
   --> /home/master/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/2a1a5f2/fedimint-core/src/task.rs:409:26
    |
409 |             tokio::task::Builder::new()
    |                          ^^^^^^^ could not find `Builder` in `task`
    |
help: consider importing one of these items
    |
400 +     use bitcoin30::script::Builder;
    |
400 +     use bitcoin::blockdata::script::Builder;
    |
400 +     use std::thread::Builder;
    |
400 +     use tokio::runtime::Builder;
    |
help: if you import `Builder`, refer to it directly
    |
409 -             tokio::task::Builder::new()
409 +             Builder::new()
    |

error[E0433]: failed to resolve: could not find `Builder` in `task`
   --> /home/master/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/2a1a5f2/fedimint-core/src/task.rs:421:26
    |
421 |             tokio::task::Builder::new()
    |                          ^^^^^^^ could not find `Builder` in `task`
    |
help: consider importing one of these items
    |
400 +     use bitcoin30::script::Builder;
    |
400 +     use bitcoin::blockdata::script::Builder;
    |
400 +     use std::thread::Builder;
    |
400 +     use tokio::runtime::Builder;
    |
help: if you import `Builder`, refer to it directly
    |
421 -             tokio::task::Builder::new()
421 +             Builder::new()
    |

For more information about this error, try `rustc --explain E0433`.
error: could not compile `fedimint-core` (lib) due to 2 previous errors
```

It seems that the conditional dependencies like tokio with features like `tracing` are not being included
```toml
[target.'cfg(not(target_family = "wasm"))'.dependencies]
(...)
tokio = { version = "1.25.0", features = ["full", "tracing"] }
```
Trying to add that as dependency or as patch to the root Cargo.toml doesn't help.

**Comment by douglaz** [comment]
Ok, the solution is to add
```toml
[build]
rustflags = ["--cfg", "tokio_unstable"]
```
to `.cargo/config.toml`
