### ISSUE TITLE
prosody config is different than what prosody_config_writer shows

### ISSUE THREAD

**Issue by otech47** [fedimint/fedimint#3724]
I deployed a federation with 

`curl -sSL https://raw.githubusercontent.com/fedimint/fedimint/master/docker/tls-download-mutinynet.sh | bash`

everything worked perfectly and federation setup was smooth.

However i went to check the prosody config file in `/etc/prosody` by doing

```
docker ps        // get container ID
docker exec -it <container_id> bash
cat /etc/prosody/prosody.cfg.lua
```

and the output is the [default prosody config](https://prosody.im/doc/example_config) instead of what is written in [prosody_config_writer](https://github.com/fedimint/fedimint/blob/master/docker/full-tls-mutinynet/docker-compose.yaml#L244)

could the writer not be working properly? or is prosody maybe overwriting the file upon installation? not sure when the `prosody_config_writer` actually executes?

**Comment by otech47** [comment]
@douglaz

**Comment by douglaz** [comment]
```yaml
  xmpp:
    image: fedimint/xmpp-prosody-chat-server:master
    command:
      - prosody
      - --config
      - /prosody_data/prosody.cfg.lua
```
You should look at `/prosody_data/prosody.cfg.lua`
