### ISSUE TITLE
Handle backport issue opening failure 

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3901]
https://github.com/fedimint/fedimint/issues/3887

@bradleystachurski plz explain

**Comment by bradleystachurski** [comment]
Capturing weekly dev sync chat from @benthecarman:

> probably just need to add this to the workflow

```
# Only run one at a time per branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 
```
