### ISSUE TITLE
Container action copypasta

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#7231]
GitHub Actions has a [matrix build](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow) feature that would allow us to massively de-duplicate the code of our container CI pipeline. The only drawback I can see, and that we might be able to work around, is that we might only want to publish if the whole run succeeds (is that even important in practice?). Am I missing anything @bradleystachurski?

https://github.com/fedimint/fedimint/blob/ae88cd982893987f23702330c95f270a9698a5b2/.github/workflows/ci-nix.yml#L321-L373

I've gotten interested because I was considering a second dimension to that matrix: x86/ARM https://github.com/fedimint/fedimint/issues/3006

<details><summary>AI Thoughts on the solution to the atomicity problem</summary>
<p>

Yes, you can create a GitHub Actions workflow that builds Docker images in a matrix step and then uploads them to Docker Hub in a final step that runs only when all matrix jobs succeed. Here's how you can do it:

```yaml
name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['app1', 'app2', 'app3']
        include:
          - image: app1
            dockerfile: ./app1/Dockerfile
            context: ./app1
          - image: app2
            dockerfile: ./app2/Dockerfile
            context: ./app2
          - image: app3
            dockerfile: ./app3/Dockerfile
            context: ./app3
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: false
          tags: ${{ github.repository_owner }}/${{ matrix.image }}:${{ github.sha }}
          outputs: type=docker,dest=/tmp/${{ matrix.image }}.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.image }}
          path: /tmp/${{ matrix.image }}.tar
          retention-days: 1

  push:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: /tmp/artifacts
      
      - name: Load and push images
        run: |
          for image in app1 app2 app3; do
            docker load --input /tmp/artifacts/$image/$image.tar
            docker push ${{ github.repository_owner }}/$image:${{ github.sha }}
            docker tag ${{ github.repository_owner }}/$image:${{ github.sha }} ${{ github.repository_owner }}/$image:latest
            docker push ${{ github.repository_owner }}/$image:latest
          done
```

Here's how this workflow works:

1. The `build` job creates a matrix of builds for different Docker images.
   - Each matrix entry specifies an image name, Dockerfile path, and build context.
   - It builds each Docker image but doesn't push them yet.
   - Instead, it saves each image as a tar file and uploads it as a GitHub Actions artifact.

2. The `push` job depends on the `build` job, meaning it will only run if all matrix builds succeed.
   - It's configured to run only on the main branch and not in pull requests.
   - It logs in to Docker Hub using your stored secrets.
   - It downloads all the Docker image artifacts from the previous step.
   - It loads each image from the tar file and pushes it to Docker Hub with both the commit SHA and 'latest' tags.

To use this workflow, you'll need to:

1. Add your Docker Hub credentials as GitHub repository secrets:
   - `DOCKERHUB_USERNAME`
   - `DOCKERHUB_TOKEN` (use an access token, not your password)

2. Adjust the matrix configuration to match your actual Docker images and their locations in your repository.

3. Place this workflow in a `.github/workflows/docker-build-push.yml` file in your repository.

This approach ensures that images are only uploaded to Docker Hub when all builds are successful, providing better reliability for your Docker image releases.

</p>
</details>
